export const COLORES_HEX: Record<string, string> = {
  'blanco':           '#FFFFFF',
  'off white':        '#F5F1EC',
  'crema':            '#FFF8E7',
  'beige':            '#E8DCC8',
  'dulce de leche':   '#C4925A',
  'camel':            '#C19A6B',
  'habano':           '#9C7A5B',
  'chocolate':        '#5C3317',
  'visón':            '#8B7355',
  'gris topo':        '#9E9589',
  'gris':             '#888888',
  'silver':           '#C0C0C0',
  'negro':            '#1A1917',
  'gold':             '#C9A84C',
  'amarillo':         '#F5C518',
  'naranja quemado':  '#CC5500',
  'coral':            '#E8705A',
  'rojo':             '#CC1111',
  'cherry':           '#800020',
  'fucsia':           '#EE0088',
  'rosa pimienta':    '#D4506A',
  'rosa palo':        '#E8B4B8',
  'rosa empolvado':   '#D4A0A7',
  'rosa nude':        '#E8C5BA',
  'púrpura':          '#7B2D8B',
  'turquesa':         '#30C4B8',
  'verde menta':      '#A8E6B8',
  'verde salvia':     '#8FAF8B',
  'verde canard':     '#1A6B5A',
  'verde oliva':      '#7A8040',
  'verde safari':     '#6B8B50',
  'verde militar':    '#4A5330',
  'azul cielo':       '#87CEEB',
  'azul maya':        '#4A8EC4',
  'azul royal':       '#2855A0',
  'blue jean':        '#5B7FA6',
  'azul marino':      '#0A1F5C',
};

export const LISTA_COLORES = Object.keys(COLORES_HEX);
